### ISSUE TITLE
How to use the code

### ISSUE THREAD

**Issue by andypinxinliu** [raruidol/ArgumentEvaluation#1]
Hi, I really like your idea of using GNN to represent the debate in the graph structure and congrats its been accepted in the journal. Would you mind share how to use the code, or if you have an unfinished repo that is not clean but reproducible to share it with me? 

Thanks!

**Comment by raruidol** [comment]
Hi Andy,

You should be able to run the code by executing the debate_evaluation.py script. Previous to that, you must place the data in the corresponding directory.

Cheers,

Ramon

**Comment by andypinxinliu** [comment]
Hi,

Thanks! Appreciate your help.

Best,
Andy
